### PR TITLE
Adding option to disable tab title change and updating docs

### PR DESCRIPTION
**Pull request by AndrewRayCode**
I do not like you touching my tabs, sir.

### CODE REVIEW

**Comment by AndrewRayCode** [comment]
ping ping @amiorin

**Comment by amiorin** [comment]
I'm busy this week. I'll merge asap.
Thx for the patience.

Il giorno 08/lug/2013, alle ore 06:38, Andrew Ray notifications@github.com
ha scritto:

ping ping @amiorin https://github.com/amiorin

—
Reply to this email directly or view it on
GitHubhttps://github.com/amiorin/vim-project/pull/6#issuecomment-20585333
.

**Comment by AndrewRayCode** [comment]
"asap" @amiorin  ;)

**Comment by jmlucjav** [comment]
I am starting to use this plugin, and adding this would greatly improve the value of the plugin

**Comment by AndrewRayCode** [comment]
Closing this @jmlucjav @amiorin and reopened https://github.com/amiorin/vim-project/pull/8 as a different branch so I can track my own fixes in my own master

**Pull request closed without merging**
